Fix YAML workflow and set correct path for backup.sh

diff --git a/.github/workflows/backup-test.yml b/.github/workflows/backup-test.yml
--- a/.github/workflows/backup-test.yml
+++ b/.github/workflows/backup-test.yml
@@ -1,8 +1,3 @@
-- name: Set execute permission for script
-  run: chmod +x linux-tar-bacup/backup.sh
-
-- name: Run backup script
-  run: ./linux-tar-bacup/backup.sh
 name: Backup Script Test
 
 on:
@@ -16,20 +11,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Set execute permission for script
-      run: chmod +x backup.sh
+      - name: Set execute permission for script
+        run: chmod +x linux-tar-bacup/backup.sh
 
-    - name: Run backup script
-      run: ./backup.sh
+      - name: Run backup script
+        run: ./linux-tar-bacup/backup.sh
 
-    - name: Check backup file exists
-      run: |
-        BACKUP_FILE=$(ls backups/test_proje_*.tar.gz)
-        if [ ! -f "$BACKUP_FILE" ]; then
-          echo "Backup file not found!"
-          exit 1
-        fi
+      - name: Check backup file exists
+        run: |
+          BACKUP_FILE=$(ls linux-tar-bacup/backups/test_proje_*.tar.gz)
+          if [ ! -f "$BACKUP_FILE" ]; then
+            echo "Backup file not found!"
+            exit 1
+          fi
 
